version: '3.8'

services:
  munira-app:
    build: .
    container_name: munira-landing-page
    restart: always
    ports:
      - "3200:3200"
    volumes:
      - ./database:/app/prisma/data
    environment:
      - DATABASE_URL=file:/app/prisma/data/prod.db
      - JWT_SECRET=change_this_to_something_secure
      - ADMIN_USER=admin
      - ADMIN_PASS=admin123
      - PORT=3200
      - NODE_ENV=production
